### ISSUE TITLE
Compilation error on deploy

### ISSUE THREAD

**Issue by brianflanagan** [will-wow/webpacker-svelte#1]
Thanks for this – super useful. But I'm having issues deploying. The build is failing on Heroku:

```
Compiling...
Compilation failed:
ModuleNotFoundError: Module not found: Error: Can't resolve 'webpacker-svelte'
```

Tried adding the package as dependency (vs devDependency) but no dice.

Am I doing something stupid?

**Comment by brianflanagan** [comment]
nevermind – it was that dependency issue. have included a pr for the readme change.

**Comment by will-wow** [comment]
Hey! I'm sorry I missed the emails about you issue, but thanks for fixing it in a PR! That seems like a reasonable update to me to fix heroku deploys.

I'm merging it in now, but out of curiosity, did you end up using this library in your project? I'd love to know how it went!
